In [1]:
import numpy as np
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [4]:
b=np.array([(1,2,3,4),(2,3,4,5)])
b

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [5]:
b[0][1]

2

In [6]:
b[0][1]=8
b

array([[1, 8, 3, 4],
       [2, 3, 4, 5]])

In [7]:
b

array([[1, 8, 3, 4],
       [2, 3, 4, 5]])

In [10]:
b.size

8

In [15]:
c=np.array([b,b])

In [16]:
c

array([[[1, 8, 3, 4],
        [2, 3, 4, 5]],

       [[1, 8, 3, 4],
        [2, 3, 4, 5]]])

In [17]:
c=np.arange(10)

In [18]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
d=np.linspace(1,5,8)

In [23]:
d

array([1.        , 1.57142857, 2.14285714, 2.71428571, 3.28571429,
       3.85714286, 4.42857143, 5.        ])

In [24]:
a.sum()

10

In [25]:
a.ndim

1

In [26]:
c.ndim

1

In [27]:
d.ndim

1

In [28]:
a.itemsize

4

In [29]:
a.dtype

dtype('int32')

In [30]:
a.size

4

In [31]:
a.shape

(4,)

In [32]:
b.shape

(2, 4)

In [33]:
a.size*a.itemsize

16

In [34]:
b=np.array([(1,2,3),(3,4,5),(8,9,0)])
b

array([[1, 2, 3],
       [3, 4, 5],
       [8, 9, 0]])

In [35]:
b.ndim

2

In [36]:
b.shape

(3, 3)

In [37]:
b.itemsize

4

In [38]:
b=np.array([(1,2,3),(3,4,5),(8,9.894567891234,0)])
b

array([[1.        , 2.        , 3.        ],
       [3.        , 4.        , 5.        ],
       [8.        , 9.89456789, 0.        ]])

In [39]:
b.ndim

2

In [40]:
b.itemsize

8

In [41]:
b.size*b.itemsize

72

In [42]:
s=np.array(['sanjana','mutkiri'])
s

array(['sanjana', 'mutkiri'], dtype='<U7')

In [43]:
s.itemsize

28

In [44]:
c=np.array(['a','b','c'])

In [45]:
c

array(['a', 'b', 'c'], dtype='<U1')

In [46]:
c.itemsize

4

In [51]:
b=b.reshape(3,3)

In [52]:
b

array([[1.        , 2.        , 3.        ],
       [3.        , 4.        , 5.        ],
       [8.        , 9.89456789, 0.        ]])

In [53]:
b=np.array([(1,2,3),(3,4,5),(8,9,0),(9,1,2)])
b

array([[1, 2, 3],
       [3, 4, 5],
       [8, 9, 0],
       [9, 1, 2]])

In [57]:
b=b.reshape(2,6)

In [58]:
b

array([[1, 2, 3, 3, 4, 5],
       [8, 9, 0, 9, 1, 2]])

In [59]:
b.min()




0

In [60]:
b.max()

9

In [61]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [62]:
np.sum(a,axis=0)

10

In [64]:
np.sum(b,axis=1)

array([18, 29])

In [65]:
np.log10(a)

array([0.        , 0.30103   , 0.47712125, 0.60205999])

In [66]:
b=np.array([(1,2,3,4),(5,6,7,8)])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [67]:
f=np.array([(9,8,7,6),(1,2,3,4)])
f

array([[9, 8, 7, 6],
       [1, 2, 3, 4]])

In [69]:
np.vstack((b,f))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 8, 7, 6],
       [1, 2, 3, 4]])

In [70]:
np.hstack((b,f))

array([[1, 2, 3, 4, 9, 8, 7, 6],
       [5, 6, 7, 8, 1, 2, 3, 4]])

In [72]:
 three=np.array([
     [[1,2,3],[4,5,6]],
     [[6,7,8],[3,0,4]]
                ])

In [73]:
three

array([[[1, 2, 3],
        [4, 5, 6]],

       [[6, 7, 8],
        [3, 0, 4]]])

In [74]:
three.ndim

3

In [75]:
three.size

12

In [76]:
three.itemsize

4

In [78]:
three.reshape(2,6)

array([[1, 2, 3, 4, 5, 6],
       [6, 7, 8, 3, 0, 4]])

In [79]:
three.ndim

3

In [81]:
for i in three.flatten():
    print(i,end=" ")

1 2 3 4 5 6 6 7 8 3 0 4 

In [84]:
for i in three:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
6
7
8
3
0
4


In [85]:
for i in three.ravel():
    print(i,end=" ")

1 2 3 4 5 6 6 7 8 3 0 4 

In [86]:
zeros=np.zeros(5)

In [87]:
zeros

array([0., 0., 0., 0., 0.])

In [89]:
zeros=np.zeros(20).reshape(4,5)

In [90]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [91]:
ones=np.ones(10)

In [98]:
ones.astype(int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [99]:
range=np.arange(2.3,4.5)

In [100]:
range

array([2.3, 3.3, 4.3])

In [101]:
#arange support decimal number also range not supports

In [102]:
b+2

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

ones

In [103]:
np.sum(ones)

10.0

In [104]:
b*2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [105]:
b.T#transpose

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [106]:
b[1,]

array([5, 6, 7, 8])

In [108]:
b[0,]

array([1, 2, 3, 4])

In [112]:
full=np.full(10,5)

In [113]:
full

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [114]:
full=np.full((2,2),7)
full

array([[7, 7],
       [7, 7]])

In [115]:
full=np.full((4,7,7),3)

In [116]:
full

array([[[3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3]],

       [[3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3]],

       [[3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3]],

       [[3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3]]])

In [118]:
list1=[[1,2,3],[4,5,6]]
list2=[[4,5,6],[3,4,5]]
list1+list2

[[1, 2, 3], [4, 5, 6], [4, 5, 6], [3, 4, 5]]

In [119]:
list1=np.array([(1,2,3),(4,5,6)])
list2=np.array([(1,2,3),(4,5,6)])
list1+list2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [120]:
list1*list2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [123]:
list1.min()

1

In [126]:
list1.mean()

3.5

In [127]:
list1.std()

1.707825127659933

In [128]:
list1.var()

2.9166666666666665

In [129]:
np.sqrt(list1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [131]:
np.var(list1)

2.9166666666666665

In [132]:
#axis=1 means rows
b.min(axis=1)

array([1, 5])

In [133]:
b.min(axis=0)

array([1, 2, 3, 4])

In [135]:
b.min()

1

In [136]:
b.std(axis=1)

array([1.11803399, 1.11803399])

In [137]:
b.std(axis=0)

array([2., 2., 2., 2.])

In [ ]:
#append

In [138]:
a=np.arange(6)

In [139]:
a

array([0, 1, 2, 3, 4, 5])

In [140]:
np.append(a,2)#only append not chane existing array

array([0, 1, 2, 3, 4, 5, 2])

In [141]:
np.append(a,(4,5,6))

array([0, 1, 2, 3, 4, 5, 4, 5, 6])

In [143]:
np.add(a,5)

array([ 5,  6,  7,  8,  9, 10])

In [144]:
a

array([0, 1, 2, 3, 4, 5])

In [145]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [149]:
new=np.array([1,2,3])

In [150]:
np.append(b,new)

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3])

In [151]:
b.ndim

2

In [152]:
np.transpose(b)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [153]:
a>4

array([False, False, False, False, False,  True])

In [154]:
a<10

array([ True,  True,  True,  True,  True,  True])

In [155]:
a[a>4]

array([5])

In [160]:
a.shape=(2,3)

In [161]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [162]:
np.random.randint(10,20,(5,5))

array([[10, 16, 19, 11, 14],
       [15, 11, 15, 12, 12],
       [10, 15, 18, 18, 11],
       [17, 15, 16, 13, 12],
       [10, 17, 10, 16, 11]])

In [163]:
letters=list('aeiou')

In [164]:
np.random.choice(letters,5)

array(['o', 'a', 'i', 'a', 'i'], dtype='<U1')

In [165]:
np.random.choice(letters,5,replace=False)

array(['i', 'a', 'e', 'u', 'o'], dtype='<U1')

In [169]:
np.random.choice(letters,7,p=[0.4,0.3,0.1,0.1,0.1])

array(['o', 'a', 'e', 'u', 'a', 'e', 'e'], dtype='<U1')

In [170]:
array=np.random.randint(10,20,(5,5))
np.save('array_file',array)

In [171]:
array2=np.load('array_file.npy')
array2

array([[16, 18, 11, 17, 17],
       [16, 16, 17, 14, 17],
       [18, 18, 19, 11, 16],
       [15, 19, 13, 15, 19],
       [16, 12, 19, 11, 11]])